---
- name: Update and configure CentOS
  hosts: docker
  become: true
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
      become: true

    - name: Upgrade yum packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
      become: true

    - name: Enable PasswordAuthentication in ssh_config
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^#\s*PasswordAuthentication\syes'
        line: 'PasswordAuthentication yes'
      become: true

    - name: Enable and restart sshd
      systemd:
        name: sshd
        state: restarted
        enabled: true
      become: true

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present
      become: true

    - name: Add Docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      become: true

    - name: Install Docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: true

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: true
      become: true

#    - name: Pull Nginx Docker image
#      docker_image:
#        name: nginx
#        source: pull
#        state: present
#      become: true
#
#    - name: Run Nginx container
#      docker_container:
#        name: c1
#        image: nginx
#        state: started
#        restart_policy: unless-stopped
#        published_ports:
#          - "81:80"
#      become: true

